### ISSUE TITLE
Kill the 2.x.3 The Error Stream sections

### ISSUE THREAD

**Issue by zostay** [zostay/P6SGI#25]
This section is not really necessary anymore.

**Comment by 0x1F602** [comment]
So how are you going to handle errors in this implementation? The 2.x.3 sections seem to suggest that all three layers share the same error stream(s).

**Comment by zostay** [comment]
The error streams aren't going away. I just don't think a separate subsection is required to describe something so simple.

**Comment by zostay** [comment]
I changed my mind. I'm not going to drop this section for now.
