### ISSUE TITLE
Rename all the p6sgi bits to p6w

### ISSUE THREAD

**Issue by zostay** [zostay/P6SGI#28]
You know, p6sgix is annoying. I think I'd rather just change it all to p6w.\* or p6wx.\* in the environment. The special headers then become P6W- or P6Wx-.

I think I like this better. I like using P6W as the abbreviation for this spec too. Dunno though. That might be taking it too far.

**Comment by zostay** [comment]
Actually, I'm rethinking the entire name completely. It's a brave new world and maybe we need to break away from some of the old naming conventions entirely. I still might go with p6w, but after sitting with Gloria Wall at PPW and having her suggest several names, I started thinking about things ending in API that might be fun. However, API is too boorish to really consider. What about "appi"? Sappi? Wappi? Swappi? My wife suggests Happi. According to [Sterling's Truths for Life #1](http://sterling.hanenkamp.com/stfl/1.html), I probably should go with that, but maybe not.

Anyway, there are more options.

**Comment by muraiki** [comment]
Yeah, I think there's no real reason to stick with something sgi-like. I'm all for names that don't try to encompass the various technologies they use. :)

I like Happi, but it looks like there's a few tiny projects on github with the same name. That being said, finding an unused name is pretty much impossible I imagine. A happi is also a type of garment: https://en.wikipedia.org/wiki/Happi

**Comment by zostay** [comment]
I noticed that. A Happi would make for a cute logo if we want a logo. For some reason, I now I have a strong desire to sing [Klimpaloon](https://www.youtube.com/watch?v=KAYKVFxZi14).

**Comment by zostay** [comment]
The latest 0.7.Draft has renamed the internal variables to p6w and p6wx, which matches well to my suggested script suffix. I'm still contemplating the greater name change.

**Comment by jjn1056** [comment]
I think the name change is a great idea, others have gone that road, like node did Connect (https://github.com/senchalabs/connect#readme) and microsoft has http://owin.org which are both interesting things to look at for paths people took.

**Comment by zostay** [comment]
I'm thinking a name change is necessary at this point. Crust is gaining momentum as the PSGI for Perl 6 implementation. I would prefer that hadn't happened, but it is and it uses the term P6SGI for various bits that have nothing to do with this spec.

**Comment by jjn1056** [comment]
@zostay why did Crust even start?  It looks to me like they took the path we all complained about a year ago, and they you took heed of it and did something better?

**Comment by zostay** [comment]
Good questions, but I can't answer them.

**Comment by zostay** [comment]
Maybe I'll rename it to BTYOGI, Better Than Your Old Gateway Interface.

**Comment by zostay** [comment]
It is finished.
