### ISSUE TITLE
Harikiri terminology

### ISSUE THREAD

**Issue by HotelCalifornia** [zostay/P6SGI#37]
This is a pretty trivial issue, but here it is anyway:

I assume `Harikiri` in `Harikiri mode` is supposed to reference Japanese ritual self-disembowelment, but this ritual is actually called `Harakiri` (with an 'a'), which means 'stomach-cutting.'

So yeah, trivial.

**Comment by zostay** [comment]
Thanks. Yep, that's a typo. It should be Harakiri.
